### ISSUE TITLE
Only two datepickers can share an id.

### ISSUE THREAD

**Issue by NachoFront** [qodesmith/datepicker#97]
const picker = datepicker('.start',{ id: 1, });
const end = datepicker('.end', { id: 1 , })

<input type="text" id="date1" class="start">
<input type="text" id="date2" class="end">

**Comment by qodesmith** [comment]
@NachoFront what are you trying to do? The `id` property is only intended to be shared by two pickers to form a date range pair.

**Comment by NachoFront** [comment]
@qodesmith 
how can i use 2 date pickers to display a range?

**Comment by qodesmith** [comment]
What version are you using? Try using the latest which is `5.14.1`. I'm not getting that error with the latest version.

**Comment by qodesmith** [comment]
Make that `5.14.2`. I just merged someone's PR with an unrelated change.

**Comment by NachoFront** [comment]
tested 5.14.2 still not working
I have solved it like this:
`let time = (new Date()).getTime();
    
    this.datePickerStart = datepicker('#startDate', { 
      alwaysShow:true,
      customDays: ['L', 'M', 'X', 'J', 'V', 'S', 'D'],
      customMonths: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
      id:  time,
    });
    this.datePickerEnd = datepicker('#endDate', { 
      alwaysShow:true ,
      customDays: ['L', 'M', 'X', 'J', 'V', 'S', 'D'],
      customMonths: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
      id: time,
    });`

**Comment by qodesmith** [comment]
@NachoFront Given the fact that I see you're doing `this.datepickerStart...` leads be to believe whatever class method this datepicker code is in is probably being called _more than once_, and that's why you're getting the error. And since `let time = (new Date()).getTime()` will give you a new value each time it is run, it's now working.

I think you need to look through your code and see when that method is being called. I would put a `console.log('daterange created!')` right after the `this.datePickeEnd` declaration and see if it logs more than once.
